# Section 1 exercise
name: Actions Workflow

on: [pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -als
          echo "sha: $GITHUB_SHA"
          echo "Repository name: $GITHUB_REPOSITORY"
          echo "My workspace: $GITHUB_WORKSPACE"

      # Clone repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List files after checkout
        run: |
          pwd
          ls -als
      - name: Simple JS action
        id: greet
      # Reference to an action. Here we can use an already published Github-Action or a local one.
        uses: actions/hello-world-javascript-action@v1.1
        # Input/output
        with:
          who-to-greet: Julio Briones
      - name: Log Greeting time
        run: echo "${{ steps.greet.time }}"