name: Matrix
on: [push]

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node -v
      - name: Change node version
        uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log changed node version
        run: node -v