name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello world!"

      - name: Multiple scripts
        run: |
          echo "[INFO] Printing Node version"
          node -v
          echo "[INFO] Printing Python version"
          python --version
          echo "[INFO] Printing NPM version"
          npm -v