name: Shell Commands

on:
#  repository_dispatch:
#    types: [build]
  # schedule:
    # Cron description: min hrs d m dw
    # * means any value
    # - cron: "* * * <+"
  # push:
  pull_request:
    # Only execute workflow when merging to `main` branch
    branches:
      - main
      # Run workflow when matching `feature/whatever_comes_after except when it has the `/`
      # But if double asterisk `**` it'll match anything after `feature/`
      - "feature/*"
      # Ignore branch example
      - "!dev"
      - "!qa"
    # Filter by tags
    tags:
      - v1.*
    # Filter by path == filename
    paths:
      - "**.js"
      # Ignore such file(s)
      - "!filename.js"

    types: [closed, assigned, opened, reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      # The payload was input in Postman.
      - name: Retrieve Payload Data
        run: echo "${{ github.event.client_payload.env }}"
      - name: Echo a string
        run: echo "Hello world!"

      - name: Multiple scripts
        run: |
          echo "[INFO] Printing Node version"
          node -v
          echo "[INFO] Printing Python version"
          python --version
          echo "[INFO] Printing NPM version"
          npm -v

      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows-command:
    runs-on: windows-latest

    # If it depends on a job finishing previously
    needs: [run-shell-command]
    steps:
      - name: Directory Powershell
        run: pwd

      - name: Directory Bash
        run: pwd
        shell: bash